# Generated by Django 3.1 on 2020-11-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_presscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='categories',
            field=models.ManyToManyField(related_name='Presss', to='team.PressCategory'),
        ),
    ]
