# Generated by Django 3.1 on 2020-11-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_press_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PressCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='media',
            new_name='name',
        ),
    ]
