# Generated by Django 3.1.4 on 2021-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('nickname', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
