# Generated by Django 3.0.8 on 2020-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='call_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='inventory',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
