# Generated by Django 3.0.8 on 2020-07-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200730_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
