# Generated by Django 3.0.8 on 2020-08-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200804_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='이름',
        ),
    ]
