# Generated by Django 3.0.8 on 2020-08-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200804_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_call',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='최대판매량'),
        ),
        migrations.AddField(
            model_name='post',
            name='min_call',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='최소판매량'),
        ),
        migrations.AddField(
            model_name='post',
            name='target_call',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='목표판매량'),
        ),
    ]
