# Generated by Django 3.0.8 on 2020-08-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200805_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.TextField(max_length=255, null=True, verbose_name='메뉴'),
        ),
    ]
