# Generated by Django 3.0.8 on 2020-08-05 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200805_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitcount',
            old_name='lists',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 5, 6, 55, 28, 153628, tzinfo=utc), null=True),
        ),
    ]
