# Generated by Django 3.0.8 on 2020-08-06 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200805_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_owner',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price_details',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='store_info',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 6, 3, 59, 4, 490286, tzinfo=utc), null=True),
        ),
    ]
