# Generated by Django 3.1 on 2020-08-06 11:20

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200806_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
