# Generated by Django 3.1 on 2020-08-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200806_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
