# Generated by Django 3.1 on 2020-08-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_post_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guide',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
