# Generated by Django 3.1 on 2020-08-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price_details',
            field=models.TextField(max_length=2550, null=True),
        ),
    ]
