# Generated by Django 3.0.8 on 2020-08-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200813_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discounted',
            field=models.IntegerField(default=0, null=True, verbose_name='할인가'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='정가'),
        ),
    ]
