# Generated by Django 3.0.8 on 2020-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200814_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='blog/images'),
        ),
    ]
