# Generated by Django 3.0.8 on 2020-08-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200814_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='guide',
            field=models.TextField(max_length=2550, null=True),
        ),
    ]
