# Generated by Django 3.0.8 on 2020-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200815_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.AlterField(
            model_name='post',
            name='guide',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message_owner',
            field=models.TextField(max_length=2550, null=True),
        ),
    ]
