# Generated by Django 3.0.8 on 2020-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200815_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
