# Generated by Django 3.1 on 2020-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200827_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guid',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
