# Generated by Django 3.1 on 2020-09-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('call', models.PositiveIntegerField(default=0, null=True, verbose_name='참여자수')),
                ('maxinv', models.PositiveIntegerField(default=0, null=True, verbose_name='인원')),
                ('body', models.TextField()),
                ('image1', models.ImageField(blank=True, max_length=550, null=True, upload_to='updates/images')),
                ('categories', models.ManyToManyField(related_name='feeds', to='myupdates.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=60, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('phone', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='myupdates.feed')),
            ],
        ),
    ]
