# Generated by Django 3.1 on 2020-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_on',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
