# Generated by Django 3.1 on 2020-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_auto_20200916_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='call',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='참여자수'),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
