# Generated by Django 3.1 on 2020-09-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_auto_20200916_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='last_modified',
        ),
    ]
