# Generated by Django 3.1 on 2020-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='categories',
            field=models.ManyToManyField(related_name='feeds', to='updates.Category'),
        ),
    ]
