# Generated by Django 3.1 on 2020-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_feed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='max',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='인원'),
        ),
    ]
