# Generated by Django 3.1 on 2020-09-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_feed_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image1',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='updates/images'),
        ),
    ]
