# Generated by Django 3.1 on 2020-09-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_feed_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='max',
            new_name='maxinv',
        ),
    ]
