# Generated by Django 3.0.8 on 2020-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daemun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_images2',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='page/images'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_images3',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='page/images'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_images4',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='page/images'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_images5',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='page/images'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_images6',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to='page/images'),
        ),
    ]
